services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  postgres:
    image: timescale/timescaledb-ha:pg15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: candles
    ports:
      - "5432:5432"